# Generated by Django 3.0.4 on 2020-03-27 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Message text')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Msg sent from')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Room name')),
                ('public', models.BooleanField(default=True, verbose_name='Room visibility')),
                ('admins', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Room owners')),
                ('messages', models.ManyToManyField(to='chat.Message', verbose_name='Messages')),
            ],
        ),
    ]
